spring.application.name=sithum-car-sale

#mysql connection
#jdbc:mysql://localhost:3306/ems?useSSL=false

spring.datasource.url=jdbc:mysql://localhost:3306/carsale?useSSL=false
spring.datasource.username=root
spring.datasource.password=Joes_kollo12345

#Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#create, create-drop
spring.jpa.hibernate.ddl-auto=update